apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tcqe0e007-python
  janus-idp.io/tekton: tcqe0e007-python
  backstage.io/kubernetes-id: tcqe0e007-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tcqe0e007-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
