apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tcqe0e007-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tcqe0e007-python 
  name: tcqe0e007-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tcqe0e007-python 
